apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-preview" .Values.analyticsService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.analyticsService.name }}
  ports:
    - port: {{ .Values.analyticsService.servicePort }}
      targetPort: {{ .Values.analyticsService.serviceTargetPort }}
  type: {{ .Values.analyticsService.serviceType }}
{{- end }}
